// <auto-generated />
namespace ProjectIA_renting_Cars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixDatabase3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixDatabase3));
        
        string IMigrationMetadata.Id
        {
            get { return "201804262036269_fixDatabase3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
